### ISSUE TITLE
Mini attachment preview into bug report attachment dialog

### ISSUE THREAD

**Issue by HalilBatuhan** [theiskaa/DevEx#9]
Should be great if you replace a mini attached image preview on numbers. (not issue but advice :D)

**Comment by theiskaa** [comment]
It will be available when [this branch](https://github.com/theiskaa/DevEx/tree/feature/bug-report) merged to develop.

**Comment by theiskaa** [comment]
Hey @HalilBatuhan the mini attachment preview image added into dialog of attachment. 
Here you can look commit changes - https://github.com/theiskaa/DevEx/commit/1f5a8db9ee9addb194a8f4ad1d70b545754265cd
